# Generated by Django 3.0.5 on 2020-04-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dojo_name', models.CharField(default='Iowa Martial Arts Des Moines', max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('picture_url', models.TextField(default='https://www.google.com/search?hl=en&sxsrf=ALeKk03td3PWu0TAdzw7a2W5BfkIkUmsMw%3A1586357941737&source=hp&ei=teaNXqHHKsaztAaT5qMo&q=3800+Merle+Hay+Rd%2C+Des+Moines%2C+IA+50310&oq=3800+Merle+Hay+Rd%2C+Des+Moines%2C+IA+50310&gs_lcp=CgZwc3ktYWIQAzICCCYyBggAEBYQHjICCCYyBQgAEM0CMgUIABDNAkoJCBcSBTEyLTc0SggIGBIEMTItMVC2FFi2FGDkHGgBcAB4AIABRIgBRJIBATGYAQCgAQKgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjh9efsi9noAhXGGc0KHRPzCAUQ4dUDCAk&uact=5#')),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=250)),
                ('instructor', models.CharField(max_length=250)),
                ('schedule', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Class_Schedules', to='martial_arts.Location')),
            ],
        ),
    ]
