# Generated by Django 3.0.5 on 2020-04-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martial_arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='picture_url',
            field=models.TextField(default='https://www.google.com/maps/vt/data=q2HB5TlSWTUrQ4rqKFu-yy5cEqZplqRNBC9Vlu4HOnj15T4-pK8zFMMrAWVuNsxiF7U-Kp26lKHJ93qC_tNlNfJIXe_2HTXxi-sdrD3tnbBt3jzGXPzvVBh1KR-ludu5O0PZ74dzbrNtieq0v4VNmgrp3gJ4zubECA'),
        ),
    ]
