# Generated by Django 3.0.5 on 2020-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martial_arts', '0002_auto_20200408_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
